### ISSUE TITLE
Can you change this project to a gradle project?

### ISSUE THREAD

**Issue by letroll** [MediaBrowser/Emby.ApiClient.Java#13]

**Comment by LukePulverenti** [comment]
it could be done yes

**Comment by RedshirtMB** [comment]
Luke, the next logical step after switching this to a gradle project would be to get it on maven. To do that you'll need to ditch the Volley dependency. All maven projects can only have maven projects as dependencies. There's an unofficial version of Volley on maven. https://github.com/mcxiaoke/android-volley

**Comment by LukePulverenti** [comment]
Thanks. I've actually forked and made modifications to volley to improve performance of it's disk cache:

https://github.com/MediaBrowser/android-volley

So I guess that either needs to be embedded or published as well. I would love to get this switched to gradle and then published. I just have not had been able to dedicate time to figuring out the maven publishing process.

**Comment by RedshirtMB** [comment]
Luke, I gave this a go this morning. Converting the project to Gradle was actually pretty easy. I've committed the changes to my fork in case you wanted to have a look. 

There are a few caveats though. 

The android support v4 library is included in the libs directory as a jar. As I mentioned above maven projects can only have other maven projects as dependencies. So this one dependency will need to be worked out somehow.

The biggest issue though is that the library doesn't seem to work properly for me. In my initial testing, the client couldn't find my server but was able to display a pin for Emby Connect. Are those pin's generated by the client? I always assumed they were supplied by the connect website.

I was going to just throw away the changes, but thought you might want to have a look first. even though it didn't work for me the generated jar's are pretty much the same size as the current ones. Only a 1-2 KB off, which I'd just attributed to a different version of Java. I use 7 because Android doesn't support Java 8

**Comment by RedshirtMB** [comment]
Turns out the no-connect wasn't a bug in my project refactor, it's due to changes in the ApiClient since I last forked on Nov 29th. With the changes since then I wasn't able to connect until I cleared the saved  credentials. Depending on how Eric's connection logic is done, all his users may need to do this after he next updates the ApiClient. Looking at his commit history I think he already knows this because he updated and then reverted his changes.

**Comment by ebr11** [comment]
What error, exactly, were you getting?

My reversion is because the current ApiClient causes my app to crash and Luke and I were never able to figure out why.

**Comment by LukePulverenti** [comment]
I meant to be targeting java 7 so if you're saying it was on 8 then that is my mistake. maybe that was the issue? Red - good stuff, although I don't know when I'll be able to take it and run with it. If by chance you're able to complete it fully then I'll merge it in.

**Comment by RedshirtMB** [comment]
I wasn't getting an error, what was happening (for me anyways) was that the ConnectionManager logic was internally rejecting the saved server credentials and the connection result would always be ConnectSignIn. Unfortunately I didn't spend any time debugging it and just assumed it was a result of my changes. Now that I've cleared the old credentials I have no way to really troubleshoot further.

Luke I wasn't accusing you of running the wrong java version, I just mentioned it because the jars were a slightly different size than my old ones, and in case you weren't aware that Android forced that Java 7 limitation. I realized this issue wasn't a result of my refactor when I reforked last night and the same thing happened with the non-altered emby code base as well.  

I'll submit a pull request for the gradle version tomorrow once I verify it's working as expected.

**Comment by RedshirtMB** [comment]
Luke, I realized I still had another device with the old stored server credentials. Here's the stacktrace for the error that's thrown after the ApiClient is updated.

![date_error](https://cloud.githubusercontent.com/assets/1930824/12706431/dbfd2356-c839-11e5-8f87-4fc807ad09a5.png)
